mcpServers:
  time:
    transport: stdio
    command: uvx
    args: [ "mcp-server-time", "--local-timezone=Asia/Taipei" ]
cacheRefreshTTL: 5m
vector:
  enabled: true
  persistent: true
  collection: tools
